name: Helloworld
title: Iyer's Website
theme: jekyll-theme-lanyon
remote_theme: poole/lanyon
version: false
description: When PhD, I Wonder
include:
  - _includes/head.html
sidebar:
  - home
  - my-cv
