name: Helloworld
title: Iyer's Website
theme: jekyll-cayman
version: false
description: When PhD, I Wonder
include:
  - _includes/head.html
sidebar:
  - home
  - my-cv
plugins:
  - jekyll-remote-theme
