name: Iyer's Website
theme: jekyll-theme-cayman
description: When PhD, I Wonder
favicon: /favicon.ico
navigation:
  - name: Home
  link: ./index.html
  - name: About
  link: ./about.html
  - name: Blog
  link: ./blog.html
