name: Iyer's Website
title: Iyer's Website
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
version: false
description: When PhD, I Wonder
include:
  - _includes/head.html
sidebar:
  - home
  - my-cv
