name: Helloworld
title: Iyer's Website
remote_theme: pages-themes/cayman@v0.2.0
version: false
description: When PhD, I Wonder
include:
  - _includes/head.html
sidebar:
  - home
  - my-cv
plugins:
  - jekyll-remote-theme
