name: Iyer's Website
theme: jekyll-theme-minimalistic
description: When PhD, I Wonder
plugins:
  - jekyll-feed
  - jekyll-seo-tag
navigation:
  - name: Home
  link: ./index.html
  - name: About
  link: ./about.html
  - name: Blog
  link: ./blog.html
